### ISSUE TITLE
Convidado da semana Suissa! #JS #MEAN

### ISSUE THREAD

**Issue by zeucxb** [CanalEuProgramador/podtech#3]
Essa semana o papo será com Suissa, deixem perguntas sobre:
- NodeJS
- Angular
- JS Funcional
- Atomic Design
- MongoDB
- MEAN
  ...

**Comment by gkal19** [comment]
Suissa, como conheceu e quando começou a programar em JS?

**Comment by wellingtonpgp** [comment]
Suissa você e foda! Wouu
