### ISSUE TITLE
Convidado da semana Willian Justen #SVG #React

### ISSUE THREAD

**Issue by wellingtonpgp** [CanalEuProgramador/podtech#8]

**Comment by ZeuCxb** [comment]
jkdsjkdjaslk

**Comment by ZeuCxb** [comment]
ksdnlkfjdslkj

**Comment by ZeuCxb** [comment]
dsjflksdjfksd

**Comment by barbier** [comment]
Quais tipos de projeto você recomenda para pessoas que estão aprendendo uma linguagem?

**Comment by marcioshiz** [comment]
- Quais conhecimentos são a base para entender bem como usar React?
- Todas as web app merecem ser SPA?

**Comment by ghost** [comment]
- Como você tem interesse em Química, tendo inclusive iniciado os estudos em uma faculdade, pretende, num futuro, trabalhar em projetos relacionando Química e Computação, ou é algo que foi mesmo descartado da sua vida?
- Como você vê a profissão de Desenvolvedores focados em **Front-end** daqui há 5 anos? Em relação a mercado de trabalho, salário e formação? Tende a melhorar, ou a tendência de desenvolvedores _full stack_ tende a ganhar mais relevância?
- Quais são as suas dicas para alguém que está ingressando nesse ramo _(Front-end)_ agora? Busca por trabalho e estudos?

Abraço!

**Comment by willianjusten** [comment]
Caramba rapaz, várias perguntas maneiras <3

**Comment by danilovaz** [comment]
Quando sai o curso de SVG?

#zoeira :joy: :joy: :joy: 
- [ ] Quais os tipos de aplicações que você vê vantagem em se utilizar o React? 
- [ ] Em termos de estrutura, qual a maior dificuldade com React, hoje?
- [ ] Você não acha "bagunçado" a forma como se programa em React? Misturando camadas e tal? Ou é questão de costume e uso das boas práticas da biblioteca?

Nozes :chestnut:

**Comment by nessacosta** [comment]
- No que um blog mudou a sua vida e sua maneira de pensar? Quais sugestões você dá para quem deseja criar um?
- Na sua opinião, por que é importante participar de eventos e ser um palestrante?
- Você largou tudo para realizar um sonho de viajar. Conte-nos como você se organizou para isso.
- Qual biblioteca você acha melhor: Angular JS ou React JS? Por quê ? Quais seriam as vantagens?

**Comment by napalmdev** [comment]
Qual é o seu fluxo de aprendizado quando quer aprender uma tecnologia nova?
