### ISSUE TITLE
Sugestão Convidado Fernando Daciuk #ReactJS

### ISSUE THREAD

**Issue by theandersonn** [CanalEuProgramador/podtech#9]

**Comment by zeucxb** [comment]
Isso é uma sugestão?

**Comment by theandersonn** [comment]
Sim @ZeuCxb é uma sugestão de convidado para o cast.

**Comment by zeucxb** [comment]
Beleza, vou falar com ele.
Em 21 de mai de 2016 12:27 PM, "Anderson Nascimento" <
notifications@github.com> escreveu:
